// flow-typed signature: fb24c74f6692c5e92fbf5362df433513
// flow-typed version: <<STUB>>/browser-cookies_v^1.2.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browser-cookies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browser-cookies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browser-cookies/src/browser-cookies' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browser-cookies/src/browser-cookies.js' {
  declare module.exports: $Exports<'browser-cookies/src/browser-cookies'>;
}
