// flow-typed signature: 3ff868b7b3860f101fcdb5adfc8892b7
// flow-typed version: <<STUB>>/utility_v^1.13.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'utility'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'utility' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'utility/lib/array' {
  declare module.exports: any;
}

declare module 'utility/lib/crypto' {
  declare module.exports: any;
}

declare module 'utility/lib/date' {
  declare module.exports: any;
}

declare module 'utility/lib/function' {
  declare module.exports: any;
}

declare module 'utility/lib/json' {
  declare module.exports: any;
}

declare module 'utility/lib/number' {
  declare module.exports: any;
}

declare module 'utility/lib/object' {
  declare module.exports: any;
}

declare module 'utility/lib/optimize' {
  declare module.exports: any;
}

declare module 'utility/lib/polyfill' {
  declare module.exports: any;
}

declare module 'utility/lib/string' {
  declare module.exports: any;
}

declare module 'utility/lib/utility' {
  declare module.exports: any;
}

declare module 'utility/lib/web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'utility/lib/array.js' {
  declare module.exports: $Exports<'utility/lib/array'>;
}
declare module 'utility/lib/crypto.js' {
  declare module.exports: $Exports<'utility/lib/crypto'>;
}
declare module 'utility/lib/date.js' {
  declare module.exports: $Exports<'utility/lib/date'>;
}
declare module 'utility/lib/function.js' {
  declare module.exports: $Exports<'utility/lib/function'>;
}
declare module 'utility/lib/json.js' {
  declare module.exports: $Exports<'utility/lib/json'>;
}
declare module 'utility/lib/number.js' {
  declare module.exports: $Exports<'utility/lib/number'>;
}
declare module 'utility/lib/object.js' {
  declare module.exports: $Exports<'utility/lib/object'>;
}
declare module 'utility/lib/optimize.js' {
  declare module.exports: $Exports<'utility/lib/optimize'>;
}
declare module 'utility/lib/polyfill.js' {
  declare module.exports: $Exports<'utility/lib/polyfill'>;
}
declare module 'utility/lib/string.js' {
  declare module.exports: $Exports<'utility/lib/string'>;
}
declare module 'utility/lib/utility.js' {
  declare module.exports: $Exports<'utility/lib/utility'>;
}
declare module 'utility/lib/web.js' {
  declare module.exports: $Exports<'utility/lib/web'>;
}
